


export const metadata = {
    title: "Guitarla-Nosotros",
    description: "Generated by create next app",
  };
  


function Nosotros() {
  return (
    <div>
        <h1>Nosotros</h1>
        
    </div>
  )
}

export default Nosotros
