

export const metadata = {
    title: "Guitarla-Tienda",
    description: "Generated by create next app",
  };
  


function Tienda() {
  return (
    <div>
        <h1>Tienda</h1>
        
    </div>
  )
}

export default Tienda