import { Inter } from "next/font/google";
import 'normalize.css/normalize.css';
import '../../styles/globals.css'
import Head from "next/head";
import Header from './ui/dashboard/header'
import Footer from './ui/dashboard/footer'


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Guitarla",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <Header/>
      {children}
      <Footer/>
      
    
      
      </body>
    </html>
  );
}
