

export const metadata = {
    title: "Guitarla-Blog",
    description: "Generated by create next app",
  };
  


function Blog() {
  return (
    <div>
        <h1>Blog</h1>
        
    </div>
  )
}

export default Blog